### ISSUE TITLE
add a field to track last login

### ISSUE THREAD

**Issue by pigeonflight** [RedTurtle/collective.login_monitor#5]
It would be useful to add a field that includes the last login. The system already captures login times, it would require a slight adjustment to the queries to reflect the last login date.

**Comment by keul** [comment]
@pigeonflight The `timestamp` already contains the last login time as it's updated at every login.
What is missing?

**Comment by pigeonflight** [comment]
I see what has happened the pypi release is 0.3.1 a version from 2014, the last login information was only added in February of this year (https://github.com/RedTurtle/collective.login_monitor/blob/master/collective/login_monitor/browser/login_logger_macros.pt#L14).
When will the 0.4.x version be released to pypi?

**Comment by keul** [comment]
Right, we were waiting for some customer's feedback about a new possible feature but this never happened.
Version 0.4 released.

**Comment by pigeonflight** [comment]
@keul thanks for that!
